// Full Indian crop database with geo constraints, climate requirements, and scoring parameters.
// Geographic filtering happens BEFORE scoring — a farmer in Kerala never sees Wheat as an option.

export const CROPS = [
  // ── CEREALS ────────────────────────────────────────────────────────────────
  {
    id: 'wheat', name: 'Wheat', nameHi: 'गेहूँ', icon: '🌾', category: 'Cereal',
    season: 'Rabi', seasonHi: 'रबी', months: [10, 11, 12, 1, 2, 3],
    baseProfit: 185000, msp: 2275,
    geo: {
      states: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Madhya Pradesh', 'Rajasthan',
               'Bihar', 'Uttarakhand', 'Himachal Pradesh', 'Gujarat', 'Maharashtra',
               'West Bengal', 'Jammu', 'Delhi', 'Chandigarh'],
      latRange: [20, 32], altRange: [0, 2000],
    },
    climate: { minRain: 25, maxRain: 110, minTemp: 8, maxTemp: 30, humidity: [30, 80] },
    waterNeed: 'medium', droughtTolerance: 0.60, floodTolerance: 0.35, marketStability: 0.88,
    detail: 'Strong export demand, stable government MSP support',
    detailHi: 'मजबूत निर्यात मांग, स्थिर सरकारी MSP समर्थन',
  },
  {
    id: 'rice', name: 'Rice (Kharif)', nameHi: 'धान (खरीफ)', icon: '🌾', category: 'Cereal',
    season: 'Kharif', seasonHi: 'खरीफ', months: [5, 6, 7, 8, 9, 10],
    baseProfit: 95000, msp: 2300,
    geo: {
      states: ['West Bengal', 'Uttar Pradesh', 'Punjab', 'Andhra Pradesh', 'Telangana',
               'Tamil Nadu', 'Odisha', 'Chhattisgarh', 'Bihar', 'Assam', 'Karnataka',
               'Kerala', 'Maharashtra', 'Jharkhand', 'Haryana', 'Gujarat', 'Manipur',
               'Tripura', 'Meghalaya', 'Nagaland', 'Arunachal Pradesh', 'Mizoram', 'Sikkim'],
      latRange: [8, 30], altRange: [0, 1500],
    },
    climate: { minRain: 150, maxRain: 400, minTemp: 20, maxTemp: 38, humidity: [60, 95] },
    waterNeed: 'very-high', droughtTolerance: 0.10, floodTolerance: 0.80, marketStability: 0.82,
    detail: 'Requires high water; suited for high-rainfall or well-irrigated regions',
    detailHi: 'अधिक पानी की आवश्यकता; उच्च वर्षा या सिंचित क्षेत्रों के लिए उपयुक्त',
  },
  {
    id: 'maize', name: 'Maize', nameHi: 'मक्का', icon: '🌽', category: 'Cereal',
    season: 'Kharif', seasonHi: 'खरीफ', months: [5, 6, 7, 8, 9],
    baseProfit: 110000, msp: 2090,
    geo: {
      states: ['Karnataka', 'Andhra Pradesh', 'Telangana', 'Rajasthan', 'Madhya Pradesh',
               'Bihar', 'Uttar Pradesh', 'Himachal Pradesh', 'Uttarakhand', 'Maharashtra',
               'Gujarat', 'Punjab', 'Haryana', 'Tamil Nadu', 'Odisha', 'Jharkhand',
               'West Bengal', 'Manipur', 'Assam', 'Meghalaya', 'Nagaland'],
      latRange: [12, 32], altRange: [0, 2700],
    },
    climate: { minRain: 60, maxRain: 200, minTemp: 18, maxTemp: 38, humidity: [40, 80] },
    waterNeed: 'medium', droughtTolerance: 0.45, floodTolerance: 0.40, marketStability: 0.72,
    detail: 'Poultry and starch industry demand growing steadily',
    detailHi: 'पोल्ट्री और स्टार्च उद्योग की मांग लगातार बढ़ रही है',
  },
  {
    id: 'bajra', name: 'Bajra (Pearl Millet)', nameHi: 'बाजरा', icon: '🌾', category: 'Cereal',
    season: 'Kharif', seasonHi: 'खरीफ', months: [5, 6, 7, 8, 9],
    baseProfit: 75000, msp: 2625,
    geo: {
      states: ['Rajasthan', 'Gujarat', 'Haryana', 'Uttar Pradesh', 'Maharashtra',
               'Karnataka', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Tamil Nadu'],
      latRange: [15, 30], altRange: [0, 1500],
    },
    climate: { minRain: 20, maxRain: 80, minTemp: 25, maxTemp: 42, humidity: [20, 65] },
    waterNeed: 'very-low', droughtTolerance: 0.92, floodTolerance: 0.25, marketStability: 0.65,
    detail: 'Thrives in arid zones; excellent drought tolerance',
    detailHi: 'शुष्क क्षेत्रों में उत्कृष्ट; बेहतरीन सूखा सहनशीलता',
  },
  {
    id: 'jowar', name: 'Jowar (Sorghum)', nameHi: 'ज्वार', icon: '🌾', category: 'Cereal',
    season: 'Both', seasonHi: 'दोनों', months: [5, 6, 7, 8, 9, 10, 11],
    baseProfit: 80000, msp: 3180,
    geo: {
      states: ['Maharashtra', 'Karnataka', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh',
               'Rajasthan', 'Gujarat', 'Tamil Nadu', 'Uttar Pradesh'],
      latRange: [14, 28], altRange: [0, 1800],
    },
    climate: { minRain: 30, maxRain: 100, minTemp: 20, maxTemp: 40, humidity: [25, 70] },
    waterNeed: 'low', droughtTolerance: 0.80, floodTolerance: 0.40, marketStability: 0.68,
    detail: 'Dual-purpose grain and fodder crop; drought hardy',
    detailHi: 'अनाज और चारे दोनों के लिए उपयोगी; सूखा सहिष्णु',
  },
  // ── OILSEEDS ──────────────────────────────────────────────────────────────
  {
    id: 'mustard', name: 'Mustard', nameHi: 'सरसों', icon: '🌻', category: 'Oilseed',
    season: 'Rabi', seasonHi: 'रबी', months: [10, 11, 12, 1, 2, 3],
    baseProfit: 140000, msp: 5650,
    geo: {
      states: ['Rajasthan', 'Uttar Pradesh', 'Haryana', 'Madhya Pradesh', 'West Bengal',
               'Gujarat', 'Assam', 'Bihar', 'Punjab', 'Uttarakhand'],
      latRange: [22, 32], altRange: [0, 1500],
    },
    climate: { minRain: 20, maxRain: 70, minTemp: 8, maxTemp: 28, humidity: [30, 70] },
    waterNeed: 'low', droughtTolerance: 0.82, floodTolerance: 0.30, marketStability: 0.74,
    detail: 'Edible oil demand rising; drought-tolerant Rabi crop',
    detailHi: 'खाद्य तेल की मांग बढ़ रही है; सूखा-सहिष्णु रबी फसल',
  },
  {
    id: 'groundnut', name: 'Groundnut', nameHi: 'मूँगफली', icon: '🥜', category: 'Oilseed',
    season: 'Kharif', seasonHi: 'खरीफ', months: [5, 6, 7, 8, 9, 10],
    baseProfit: 150000, msp: 6783,
    geo: {
      states: ['Gujarat', 'Rajasthan', 'Andhra Pradesh', 'Tamil Nadu', 'Karnataka',
               'Maharashtra', 'Madhya Pradesh', 'Uttar Pradesh', 'West Bengal', 'Odisha',
               'Telangana'],
      latRange: [10, 28], altRange: [0, 1000],
    },
    climate: { minRain: 50, maxRain: 180, minTemp: 22, maxTemp: 40, humidity: [40, 75] },
    waterNeed: 'medium', droughtTolerance: 0.55, floodTolerance: 0.30, marketStability: 0.72,
    detail: 'High-value oilseed with strong processing industry demand',
    detailHi: 'उच्च-मूल्य तिलहन; प्रसंस्करण उद्योग की मजबूत मांग',
  },
  {
    id: 'soybean', name: 'Soybean', nameHi: 'सोयाबीन', icon: '🫘', category: 'Oilseed',
    season: 'Kharif', seasonHi: 'खरीफ', months: [5, 6, 7, 8, 9, 10],
    baseProfit: 130000, msp: 4892,
    geo: {
      states: ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Karnataka', 'Telangana',
               'Andhra Pradesh', 'Gujarat', 'Uttar Pradesh', 'Chhattisgarh'],
      latRange: [16, 28], altRange: [0, 1000],
    },
    climate: { minRain: 70, maxRain: 200, minTemp: 20, maxTemp: 38, humidity: [50, 85] },
    waterNeed: 'medium', droughtTolerance: 0.50, floodTolerance: 0.45, marketStability: 0.70,
    detail: 'Global protein demand supporting prices; good Kharif option',
    detailHi: 'वैश्विक प्रोटीन मांग कीमतों को सहारा दे रही है',
  },
  {
    id: 'sunflower', name: 'Sunflower', nameHi: 'सूरजमुखी', icon: '🌼', category: 'Oilseed',
    season: 'Both', seasonHi: 'दोनों', months: [2, 3, 4, 5, 6, 7, 8, 9],
    baseProfit: 120000, msp: 7280,
    geo: {
      states: ['Karnataka', 'Andhra Pradesh', 'Telangana', 'Maharashtra', 'Tamil Nadu',
               'Odisha', 'Bihar', 'Uttar Pradesh', 'Gujarat', 'Haryana', 'Punjab'],
      latRange: [12, 30], altRange: [0, 1500],
    },
    climate: { minRain: 25, maxRain: 100, minTemp: 18, maxTemp: 38, humidity: [30, 70] },
    waterNeed: 'low', droughtTolerance: 0.70, floodTolerance: 0.42, marketStability: 0.68,
    detail: 'Edible oil demand stable; suits irrigated and rainfed',
    detailHi: 'खाद्य तेल की मांग स्थिर; सिंचित और वर्षाश्रित दोनों के लिए',
  },
  // ── PULSES ────────────────────────────────────────────────────────────────
  {
    id: 'chickpea', name: 'Chickpea (Chana)', nameHi: 'चना', icon: '🫘', category: 'Pulse',
    season: 'Rabi', seasonHi: 'रबी', months: [10, 11, 12, 1, 2, 3],
    baseProfit: 165000, msp: 5440,
    geo: {
      states: ['Madhya Pradesh', 'Rajasthan', 'Uttar Pradesh', 'Maharashtra', 'Karnataka',
               'Andhra Pradesh', 'Gujarat', 'Bihar', 'Haryana', 'Punjab', 'Chhattisgarh',
               'Telangana'],
      latRange: [16, 30], altRange: [0, 1500],
    },
    climate: { minRain: 20, maxRain: 65, minTemp: 10, maxTemp: 32, humidity: [25, 65] },
    waterNeed: 'low', droughtTolerance: 0.75, floodTolerance: 0.28, marketStability: 0.62,
    detail: 'Pulse MSP increased; protein demand growing steadily',
    detailHi: 'दाल MSP बढ़ा; प्रोटीन की मांग लगातार बढ़ रही है',
  },
  {
    id: 'tur', name: 'Tur (Pigeon Pea)', nameHi: 'अरहर/तूर', icon: '🫘', category: 'Pulse',
    season: 'Kharif', seasonHi: 'खरीफ', months: [5, 6, 7, 8, 9, 10, 11],
    baseProfit: 160000, msp: 7550,
    geo: {
      states: ['Maharashtra', 'Karnataka', 'Andhra Pradesh', 'Telangana', 'Uttar Pradesh',
               'Madhya Pradesh', 'Gujarat', 'Rajasthan', 'Tamil Nadu', 'Odisha',
               'Chhattisgarh', 'Bihar', 'Jharkhand'],
      latRange: [10, 28], altRange: [0, 1500],
    },
    climate: { minRain: 60, maxRain: 180, minTemp: 20, maxTemp: 38, humidity: [40, 80] },
    waterNeed: 'low', droughtTolerance: 0.72, floodTolerance: 0.35, marketStability: 0.60,
    detail: 'High MSP; chronic supply deficit keeps prices elevated',
    detailHi: 'उच्च MSP; पुरानी आपूर्ति कमी से कीमतें ऊंची रहती हैं',
  },
  {
    id: 'moong', name: 'Moong (Green Gram)', nameHi: 'मूँग', icon: '🫘', category: 'Pulse',
    season: 'Both', seasonHi: 'दोनों', months: [3, 4, 5, 6, 7, 8, 9],
    baseProfit: 120000, msp: 8682,
    geo: {
      states: ['Rajasthan', 'Maharashtra', 'Andhra Pradesh', 'Karnataka', 'Tamil Nadu',
               'Gujarat', 'Madhya Pradesh', 'Uttar Pradesh', 'Punjab', 'Haryana',
               'Odisha', 'Bihar', 'Telangana', 'West Bengal'],
      latRange: [10, 30], altRange: [0, 1200],
    },
    climate: { minRain: 40, maxRain: 150, minTemp: 25, maxTemp: 40, humidity: [40, 80] },
    waterNeed: 'low', droughtTolerance: 0.65, floodTolerance: 0.40, marketStability: 0.63,
    detail: 'Short-duration crop; fits well as relay or catch crop',
    detailHi: 'कम अवधि की फसल; रिले या कैच क्रॉप के रूप में उपयुक्त',
  },
  // ── CASH CROPS ────────────────────────────────────────────────────────────
  {
    id: 'cotton', name: 'Cotton', nameHi: 'कपास', icon: '☁️', category: 'Cash Crop',
    season: 'Kharif', seasonHi: 'खरीफ', months: [4, 5, 6, 7, 8, 9, 10, 11],
    baseProfit: 220000, msp: 7121,
    geo: {
      states: ['Gujarat', 'Maharashtra', 'Telangana', 'Andhra Pradesh', 'Karnataka',
               'Madhya Pradesh', 'Haryana', 'Punjab', 'Rajasthan', 'Tamil Nadu'],
      latRange: [14, 30], altRange: [0, 600],
    },
    climate: { minRain: 60, maxRain: 180, minTemp: 22, maxTemp: 42, humidity: [40, 75] },
    waterNeed: 'medium', droughtTolerance: 0.52, floodTolerance: 0.35, marketStability: 0.60,
    detail: 'High-value; black cotton soil regions have natural advantage',
    detailHi: 'उच्च मूल्य; काली मिट्टी क्षेत्रों को प्राकृतिक लाभ',
  },
  {
    id: 'sugarcane', name: 'Sugarcane', nameHi: 'गन्ना', icon: '🎋', category: 'Cash Crop',
    season: 'Annual', seasonHi: 'वार्षिक', months: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    baseProfit: 280000, msp: 340,
    geo: {
      states: ['Uttar Pradesh', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Andhra Pradesh',
               'Telangana', 'Gujarat', 'Bihar', 'Haryana', 'Punjab', 'Uttarakhand'],
      latRange: [12, 28], altRange: [0, 1200],
    },
    climate: { minRain: 100, maxRain: 300, minTemp: 20, maxTemp: 40, humidity: [60, 90] },
    waterNeed: 'very-high', droughtTolerance: 0.25, floodTolerance: 0.55, marketStability: 0.82,
    detail: 'Long gestation but guaranteed FRP pricing from mills',
    detailHi: 'लंबी अवधि लेकिन मिलों से गारंटीकृत FRP मूल्य',
  },
  // ── SPICES ────────────────────────────────────────────────────────────────
  {
    id: 'turmeric', name: 'Turmeric', nameHi: 'हल्दी', icon: '🟡', category: 'Spice',
    season: 'Kharif', seasonHi: 'खरीफ', months: [5, 6, 7, 8, 9, 10, 11],
    baseProfit: 240000, msp: null,
    geo: {
      states: ['Andhra Pradesh', 'Telangana', 'Tamil Nadu', 'Odisha', 'Karnataka',
               'West Bengal', 'Maharashtra', 'Kerala', 'Assam', 'Meghalaya', 'Manipur'],
      latRange: [8, 22], altRange: [0, 1500],
    },
    climate: { minRain: 150, maxRain: 300, minTemp: 20, maxTemp: 35, humidity: [65, 90] },
    waterNeed: 'high', droughtTolerance: 0.30, floodTolerance: 0.50, marketStability: 0.65,
    detail: 'High-value spice; Nizamabad and Salem are major markets',
    detailHi: 'उच्च-मूल्य मसाला; निज़ामाबाद और सेलम प्रमुख बाज़ार',
  },
  {
    id: 'chilli', name: 'Chilli', nameHi: 'मिर्च', icon: '🌶️', category: 'Spice',
    season: 'Both', seasonHi: 'दोनों', months: [6, 7, 8, 9, 10, 11, 12, 1, 2],
    baseProfit: 200000, msp: null,
    geo: {
      states: ['Andhra Pradesh', 'Telangana', 'Karnataka', 'Tamil Nadu', 'Maharashtra',
               'Odisha', 'West Bengal', 'Rajasthan', 'Gujarat', 'Madhya Pradesh', 'Punjab'],
      latRange: [10, 28], altRange: [0, 1200],
    },
    climate: { minRain: 60, maxRain: 180, minTemp: 18, maxTemp: 38, humidity: [40, 80] },
    waterNeed: 'medium', droughtTolerance: 0.48, floodTolerance: 0.30, marketStability: 0.55,
    detail: 'India dominates global chilli exports; prices volatile but high',
    detailHi: 'भारत वैश्विक मिर्च निर्यात में अग्रणी; कीमतें अस्थिर लेकिन ऊंची',
  },
  {
    id: 'ginger', name: 'Ginger', nameHi: 'अदरक', icon: '🫚', category: 'Spice',
    season: 'Kharif', seasonHi: 'खरीफ', months: [3, 4, 5, 6, 7, 8, 9, 10, 11],
    baseProfit: 300000, msp: null,
    geo: {
      states: ['Kerala', 'Meghalaya', 'Arunachal Pradesh', 'Sikkim', 'Nagaland', 'Odisha',
               'Assam', 'West Bengal', 'Karnataka', 'Himachal Pradesh', 'Uttarakhand',
               'Manipur', 'Mizoram'],
      latRange: [8, 30], altRange: [300, 1800],
    },
    climate: { minRain: 150, maxRain: 350, minTemp: 15, maxTemp: 35, humidity: [65, 90] },
    waterNeed: 'high', droughtTolerance: 0.25, floodTolerance: 0.45, marketStability: 0.62,
    detail: 'High-value spice; export demand from Middle East and Europe growing',
    detailHi: 'उच्च-मूल्य मसाला; मध्य पूर्व और यूरोप से निर्यात मांग बढ़ रही है',
  },
  {
    id: 'large_cardamom', name: 'Large Cardamom', nameHi: 'बड़ी इलायची', icon: '🌿',
    category: 'Spice', season: 'Annual', seasonHi: 'वार्षिक',
    months: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    baseProfit: 400000, msp: null,
    geo: {
      states: ['Sikkim', 'Arunachal Pradesh', 'Nagaland', 'Meghalaya'],
      latRange: [26, 30], altRange: [600, 2000],
    },
    climate: { minRain: 200, maxRain: 500, minTemp: 12, maxTemp: 28, humidity: [75, 95] },
    waterNeed: 'high', droughtTolerance: 0.20, floodTolerance: 0.55, marketStability: 0.72,
    detail: 'High-value spice; Sikkim dominates Indian production',
    detailHi: 'उच्च-मूल्य मसाला; सिक्किम भारतीय उत्पादन में अग्रणी',
  },
  // ── VEGETABLES ────────────────────────────────────────────────────────────
  {
    id: 'potato', name: 'Potato', nameHi: 'आलू', icon: '🥔', category: 'Vegetable',
    season: 'Rabi', seasonHi: 'रबी', months: [9, 10, 11, 12, 1, 2],
    baseProfit: 210000, msp: null,
    geo: {
      states: ['Uttar Pradesh', 'West Bengal', 'Bihar', 'Punjab', 'Madhya Pradesh',
               'Gujarat', 'Himachal Pradesh', 'Assam', 'Haryana', 'Uttarakhand'],
      latRange: [22, 32], altRange: [0, 2500],
    },
    climate: { minRain: 40, maxRain: 120, minTemp: 8, maxTemp: 25, humidity: [50, 80] },
    waterNeed: 'high', droughtTolerance: 0.30, floodTolerance: 0.25, marketStability: 0.45,
    detail: 'High returns but prone to market gluts; cold storage access helps',
    detailHi: 'उच्च रिटर्न लेकिन बाज़ार में अतिरिक्त आपूर्ति का खतरा; कोल्ड स्टोरेज सहायक',
  },
  {
    id: 'onion', name: 'Onion', nameHi: 'प्याज', icon: '🧅', category: 'Vegetable',
    season: 'Both', seasonHi: 'दोनों', months: [9, 10, 11, 12, 1, 2, 3, 4, 5, 6],
    baseProfit: 180000, msp: null,
    geo: {
      states: ['Maharashtra', 'Karnataka', 'Madhya Pradesh', 'Gujarat', 'Rajasthan',
               'Bihar', 'Uttar Pradesh', 'Andhra Pradesh', 'Telangana', 'Tamil Nadu',
               'Haryana', 'West Bengal'],
      latRange: [14, 28], altRange: [0, 1000],
    },
    climate: { minRain: 30, maxRain: 100, minTemp: 12, maxTemp: 35, humidity: [35, 70] },
    waterNeed: 'medium', droughtTolerance: 0.45, floodTolerance: 0.28, marketStability: 0.42,
    detail: 'Highly volatile prices; Nashik belt has infrastructure advantage',
    detailHi: 'अत्यधिक अस्थिर कीमतें; नासिक बेल्ट को बुनियादी ढांचे का लाभ',
  },
  // ── PLANTATION ────────────────────────────────────────────────────────────
  {
    id: 'coconut', name: 'Coconut', nameHi: 'नारियल', icon: '🥥', category: 'Plantation',
    season: 'Annual', seasonHi: 'वार्षिक', months: [0,1,2,3,4,5,6,7,8,9,10,11],
    baseProfit: 160000, msp: null,
    geo: {
      states: ['Kerala', 'Tamil Nadu', 'Karnataka', 'Andhra Pradesh', 'Goa',
               'West Bengal', 'Odisha', 'Maharashtra', 'Assam', 'Tripura'],
      latRange: [8, 22], altRange: [0, 900],
    },
    climate: { minRain: 150, maxRain: 400, minTemp: 22, maxTemp: 38, humidity: [70, 95] },
    waterNeed: 'high', droughtTolerance: 0.35, floodTolerance: 0.50, marketStability: 0.78,
    detail: 'Perennial income; copra, oil, and tender coconut markets all strong',
    detailHi: 'बारहमासी आय; कोपरा, तेल और हरे नारियल के बाज़ार मजबूत',
  },
  {
    id: 'banana', name: 'Banana', nameHi: 'केला', icon: '🍌', category: 'Plantation',
    season: 'Annual', seasonHi: 'वार्षिक', months: [0,1,2,3,4,5,6,7,8,9,10,11],
    baseProfit: 250000, msp: null,
    geo: {
      states: ['Tamil Nadu', 'Maharashtra', 'Andhra Pradesh', 'Karnataka', 'Gujarat',
               'Madhya Pradesh', 'West Bengal', 'Kerala', 'Bihar', 'Assam', 'Tripura',
               'Odisha'],
      latRange: [8, 25], altRange: [0, 1200],
    },
    climate: { minRain: 100, maxRain: 300, minTemp: 22, maxTemp: 38, humidity: [65, 90] },
    waterNeed: 'high', droughtTolerance: 0.25, floodTolerance: 0.40, marketStability: 0.70,
    detail: 'Year-round income; Jalgaon and Anantapur are major producing belts',
    detailHi: 'वर्षभर आय; जलगाँव और अनंतपुर प्रमुख उत्पादन क्षेत्र',
  },
  {
    id: 'tea', name: 'Tea', nameHi: 'चाय', icon: '🍵', category: 'Plantation',
    season: 'Annual', seasonHi: 'वार्षिक', months: [0,1,2,3,4,5,6,7,8,9,10,11],
    baseProfit: 350000, msp: null,
    geo: {
      states: ['Assam', 'West Bengal', 'Tamil Nadu', 'Kerala', 'Karnataka',
               'Himachal Pradesh', 'Uttarakhand', 'Arunachal Pradesh', 'Manipur',
               'Sikkim', 'Tripura', 'Meghalaya', 'Nagaland', 'Mizoram'],
      latRange: [8, 28], altRange: [300, 2200],
    },
    climate: { minRain: 200, maxRain: 500, minTemp: 13, maxTemp: 32, humidity: [70, 95] },
    waterNeed: 'very-high', droughtTolerance: 0.20, floodTolerance: 0.55, marketStability: 0.75,
    detail: 'Perennial plantation; Assam CTC and Darjeeling orthodox fetch premium',
    detailHi: 'बारहमासी बागान; असम CTC और दार्जिलिंग ऑर्थोडॉक्स प्रीमियम पर बिकते हैं',
  },
  // ── FRUITS / HILL ─────────────────────────────────────────────────────────
  {
    id: 'apple', name: 'Apple', nameHi: 'सेब', icon: '🍎', category: 'Fruit',
    season: 'Annual', seasonHi: 'वार्षिक', months: [0,1,2,3,4,5,6,7,8,9,10,11],
    baseProfit: 500000, msp: null,
    geo: {
      states: ['Himachal Pradesh', 'Jammu & Kashmir', 'Uttarakhand', 'Arunachal Pradesh',
               'Nagaland'],
      latRange: [30, 37], altRange: [1500, 2700],
    },
    climate: { minRain: 100, maxRain: 250, minTemp: 2, maxTemp: 22, humidity: [50, 80] },
    waterNeed: 'medium', droughtTolerance: 0.40, floodTolerance: 0.35, marketStability: 0.78,
    detail: 'Premium fruit; Shimla and Kullu belt command highest prices',
    detailHi: 'प्रीमियम फल; शिमला और कुल्लू बेल्ट सर्वोच्च कीमतें पाते हैं',
  },
];

export default CROPS;
